version: '3.3'
services:
  loki:
    network_mode: cnet
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command: -config.file=/opt/docker_data/loki/local-config.yaml
    networks:
      - cnet