version: '3.3'
services:
  loki:
    network_mode: cnet
    image: grafana/loki:master
    ports:
      - "3100:3100"
    command: -config.file=/config/loki-config.yaml
    volumes:
            - '/opt/docker_data/loki/loki-config.yaml:/config/loki-config.yaml'
                          