version: '3.3'
services:
    grafana:
        network_mode: cnet
        container_name: grafana
        ports:
            - '${port_grafana}:3000'
        image: grafana/grafana

        volumes:
            - /opt/docker_data/grafana/data/grafana:/var/lib/grafana