version: '3.3'
services:
    grafana:
        user: "0"
        network_mode: cnet
        container_name: grafana
        ports:
            - '${port_grafana}:3000'
        image: grafana/grafana:latest
        environment:
            - 'GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-simple-json-datasource,alexanderzobnin-zabbix-app,grafana-piechart-panel,grafana-worldmap-panel,mxswat-separator-panel,farski-blendstat-panel,fifemon-graphql-datasource,grafana-azure-monitor-datasource,natel-discrete-panel'
 #           - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
 #           - GF_USERS_ALLOW_SIGN_UP=false
 #           - GF_SERVER_DOMAIN=myrul.com
 #           - GF_SMTP_ENABLED=true
 #           - GF_SMTP_HOST=smtp.gmail.com:587
 #           - GF_SMTP_USER=myadrress@gmail.com
 #           - GF_SMTP_PASSWORD=mypassword
 #           - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
        volumes:
            - "/opt/docker_data/grafana/data:/var/lib/grafana"