version: '3.3'
services:
    zabbix-agent:
        user: root
        privileged: true
        network_mode: cnet
        container_name: grafana-clients-zabbix-agent
        volumes:
#            - '/root/docker/zabbix/mounts/agent/etc-zabbix_agentd.d/:/etc/zabbix/zabbix_agentd.d/'
#            - '/root/docker/zabbix/mounts/agent/var_lib_modules/:/var/lib/zabbix/modules/'
#            - '/root/docker/zabbix/mounts/agent/var_lib_enc/:/var/lib/zabbix/enc/'
            - '/var/run/docker.sock:/var/run/docker.sock'
        ports:
        - 10050:10050
        environment:
            - ZBX_HOSTNAME=XXXXX-Collector-docker
            - ZBX_SERVER_HOST=zabbixint.tilsonnoc.com
            - ZBX_ENABLEREMOTECOMMANDS=1
            - ZBX_DEBUGLEVEL=0            
        image: zabbix/zabbix-agent2:latest
